CREATE TABLE IF NOT EXISTS AppointmentSlots (
    SlotID INT PRIMARY KEY AUTO_INCREMENT,
    DoctorID INT NOT NULL,
    AppointmentDate DATE NOT NULL,
    StartTime TIME NOT NULL,
    EndTime TIME NOT NULL,
    IsBooked BOOLEAN DEFAULT FALSE,
    PatientID INT DEFAULT NULL,
    ConsultType VARCHAR(128) DEFAULT NULL,
    Comments VARCHAR(1024) DEFAULT NULL
);